### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by WirthmU** [LeonGaultier/fhem-GardenaSmart#2]
after installing the 73_GardenaSmartBridge.pm module and adapting rights, when I enter the reload command in FHEM (reload 73_GardenaSmartBridge) I get the following error:

`error at ./FHEM/73_GardenaSmartBridge.pm line 787, near ") )"`

the other module (74_GardenaSmartDevice) works fine.

**Comment by CoolTuxNet** [comment]
Can you test it again with the new version?

**Comment by WirthmU** [comment]
error message with the latest version:

`error at ./FHEM/73_GardenaSmartBridge.pm line 789, near ") )"`

**Comment by CoolTuxNet** [comment]
Sorry ich can find any Error. 
how do you install the module? are you doing a fhem update?

**Comment by WirthmU** [comment]
I did a complete re-install FHEM on my device. This did correct the errors.

Thank you
