### ISSUE TITLE
Configurable URL

### ISSUE THREAD

**Issue by CoolTuxNet** [LeonGaultier/fhem-GardenaSmart#3]
SciLor:
It would be nice to have the api url configurable, as I am currently working on a project to replace the cloud with a local script running on the gateway.

**Comment by CoolTuxNet** [comment]
Which part of the URL should be configurable. The API part is an integral part in many places. I can only make the domain part dynamic.
example:
https://api.gardena.com/

**Comment by CoolTuxNet** [comment]
SciLor:
That would be enough, as I create a server on the gateway itself and I replicate the rest of the api.

**Comment by CoolTuxNet** [comment]
Then it looks good. Will work in the next few weeks.

**Comment by SciLor** [comment]
Thanks for the implementation.
See https://github.com/gardena-smart-reverse-engineering/deGardenServer/issues/1
